spring:
    application:
        name: asm
    datasource:
        url: jdbc:postgresql://localhost:5432/assignment
        username: postgres
        password: 12345
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
        ddl-auto: update
        show-sql: true
server:
    port: 8080
idp:
    url: http://localhost:8081
    client-id: assignment_app
    client-secret: kN1t0hDYHBybDRNtjyITHw1NaMATnq83