spring:
    application:
        name: asm
    datasource:
        url: jdbc:postgresql://localhost:6543/custom-provider
        username: postgres
        password: 12345
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
    security:
        oauth2:
            resourceserver:
              jwt:
                issuer-uri: http://localhost:9090/realms/Assignment
server:
    port: 8080
idp:
    url: http://localhost:9090
    client-id: assignment_app
    client-secret: VLIyo1wMGSB3fMtKZ108itxA1bq9XIjb
